export const HomePage = () => {
  return (
    <>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
    </>
  );
};
